/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pielot_helloopenal_HelloOpenAL */

#ifndef _Included_org_pielot_helloopenal_HelloOpenAL
#define _Included_org_pielot_helloopenal_HelloOpenAL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pielot_helloopenal_HelloOpenAL
 * Method:    play
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_pielot_helloopenal_HelloOpenAL_play(JNIEnv *,
		jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
